FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-12
EXPOSE 3000

ENV NODE_ENV="production"

COPY package.json ./
COPY package-lock.json ./
COPY server.js ./
COPY tsconfig.json ./
COPY webpack-config.js ./
COPY index.html ./
ADD src /src/

RUN npm install
RUN npm run-script build

CMD ["node", "server.js"]
